name: details
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencies solved by shared_dependencies module
  cupertino_icons: any

  provider: any
  flutter_bloc: any
  get_it: any
  injectable: any
  freezed_annotation: any
  json_annotation: any
  dio: any
  pretty_dio_logger: any
  mocktail: any
  bloc_test: any
  stream_transform: any
  shimmer: any
  meta: any

  # Local modules
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  test: ^1.21.4

flutter:
  uses-material-design: true
