name: list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  test: ^1.21.4

flutter:
  uses-material-design: true
