name: common
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
